version: '3.3'
services:
 py_test:
   build: .
   volumes:
     - .:/python_test
   ports:
     - "8088:8088"
   depends_on:
     - chat_db
   logging:
     driver: "json-file"
     options:
       max-size: "10k"
       max-file: "1"
 chat_db:
   image: mongo
   restart: always
   environment:
     MONGO_INITDB_DATABASE: test_db
   ports:
     - 27017:27017