version: '3.3'
services:
 py_test:
   build: .
   command: python index.py
   volumes:
     - .:/code
   ports:
     - "8088:8088"
   depends_on:
     - chat_db
 chat_db:
   image: mongo
   restart: always
   environment:
     MONGO_INITDB_DATABASE: test_db
   ports:
     - 27017:27017